### ISSUE TITLE
Bullet points on challenges of qual data, ep 01_qual-data

### ISSUE THREAD

**Issue by josenino95** [rcurty/qualdata-training#10]
I see there's three bullet points in the first section of the [01_qual-data episode](https://rcurty.github.io/qualdata-training/01_qual-data.html). The second one says "sensitivity", but that bullet point only talks about subjectivity as I see it. Maybe there's more of a reference to sensitivity in bullet point 3, so that last one could be "labor-intensive and sensitivity".

**Comment by rcurty** [comment]
That's right! I have combined it with the labor-intensive aspect of handling qual data.
