### ISSUE TITLE
Better clarification and characterization of data types in ep 01_qual-data

### ISSUE THREAD

**Issue by josenino95** [rcurty/qualdata-training#11]
I think [episode 01_qual-data](https://rcurty.github.io/qualdata-training/01_qual-data.html) could be more clear or specific on what are the considered data types. At the beginning of the page it says "This data type includes field notes, interviews, [...]", but later it says "Qualitative data types include written text, recordings and their transcriptions [...]". So I think overall this episode could have more clear characterizations of qual data, or having these organized differently: data types, sources, collection methods.

I also see that the paragraphs of  the ["Data Types in Qualitative Research" section](https://rcurty.github.io/qualdata-training/01_qual-data.html#data-types-in-qualitative-research) always start similarly, like "Qualitative data includes ...." or "Qualitative data can be collected ...". So reading it can seem repetitive.

**Comment by rcurty** [comment]
Paragraphs now include types, sources, and methods and redundancies were removed. .
