### ISSUE TITLE
Ending of ep 01_qual-data

### ISSUE THREAD

**Issue by josenino95** [rcurty/qualdata-training#12]
[Episode 01_qual-data](https://rcurty.github.io/qualdata-training/01_qual-data.html) ends with "In the next episode, we will cover ethical considerations and additional steps researchers should take when conducting research with human participants.". But the next episode is actually about DMPs

**Comment by rcurty** [comment]
Thanks for catching that! When I added the new DMP episode, I completely forgot to change that transition.
