### ISSUE TITLE
Wording of exercise in ep 03_ethics

### ISSUE THREAD

**Issue by josenino95** [rcurty/qualdata-training#14]
The exercise at the end of e[pisode 03_ethics](https://rcurty.github.io/qualdata-training/03_ethics.html) it says "... let’s access the archive for the two projects below ...", but there is only one listed resource VandeVusse, Alicia; Mueller, Jennifer. 2021

**Comment by rcurty** [comment]
Good catch! Two examples would take extra time, I forgot to adjust the text after I decided to remove the second example.
