### ISSUE TITLE
Crafting a DMP for Qualitative Research

### ISSUE THREAD

**Issue by brunj7** [rcurty/qualdata-training#8]
https://rcurty.github.io/qualdata-training/02_dmp.html#crafting-a-dmp-for-qualitative-research

Missing a space `Fortunately, creating a DMP is simplified with the help of appropriate templates.The DMPTool is an `

**Comment by brunj7** [comment]
Same section, about the access to the DMPTool -- you implies that it is a UCSB specific login; maybe mention something about UCSB researchers having access to it but what if they work with external collaborators who are not at UCSB?

**Comment by rcurty** [comment]
@brunj7 I have added "It's important to highlight that the DMPTool is free for everyone. Non-UCSB affiliates can also be added as collaborators and reviewers if desired. We encourage you to log in with your UCSB account to access tailored guidance and resources to help you craft your plan.". Does it look good?

**Comment by brunj7** [comment]
I think it is great so
